### ISSUE TITLE
Wrong score calculation

### ISSUE THREAD

**Issue by Fubi147** [Boman/AufAchseKartenSpiel#1]
See attached screenshot. Wrong calculation for end scoring value of player Klöps.

![image](https://user-images.githubusercontent.com/61831841/75980724-5a12f380-5ee3-11ea-834b-7c0aa9759f08.png)

**Comment by Boman** [comment]
There is still an issue with the scoring :-(

![image](https://user-images.githubusercontent.com/612728/75988816-766a5c80-5ef2-11ea-802f-10e45465fdab.png)

**Comment by Boman** [comment]
You should replace

>                 _ ->
>                     0

with

>                 Minus50 :: _ ->
>                     0
> 
>                 (DrawCard _) :: _ ->
>                     0
> 
>                 Discard :: _ ->
>                     0
